# Generated by Django 3.2.9 on 2021-11-12 05:08

import blog.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=blog.models.NameField(max_length=255),
        ),
    ]
